[package]
authors = ["Owen Sanchez <pengowen816@gmail.com>"]
name = "gfx-point-shadows"
version = "0.1.0"
[dependencies]
cgmath = "0.15.0"
gfx = "0.15"
gfx_app = "0.5.0"
gfx_window_glutin = "0.17.0"
glutin = "0.9.2"
